export const LIMITS = {
  BEST_SELLER_PRODUCTS_LIMITS: 12,
  CATEGORIES_LIMITS: 15,
  ELETRONIC_PRODUCTS_LIMITS: 12,
  FASHION_PRODUCTS_LIMITS: 6,
  LATEST_BLOG_LIMITS: 6,
  POPULAR_PRODUCTS_LIMITS: 14,
  POPULAR_PRODUCTS_TWO_LIMITS: 7,
  PRODUCTS_LIMITS: 15,
  RELATED_PRODUCTS_LIMITS: 20,
};
