export const enum QueryParamsKey {
  CartId = "cart-id",
  CategoryId = "cat-id",
  CategoryPath = "category-path",
  CategoryUid = "category-uid",
  Language = "lang",
  Letter = "letter",
  Locale = "locale",
  Name = "name",
  OpenApp = "open-app",
  OrderId = "order-id",
  Page = "page",
  PageSize = "page-size",
  PaymentStatus = "payment-status",
  Price = "price",
  PriceRange = "price-range",
  Search = "q",
  SetAsDefault = "set-as-default",
  Sort = "sort",
  StoreUrl = "store-url",
  Tab = "tab",
  To = "to",
}
