export const MOBILE_NAVIGATION_SECTION_NAME = "mobile-navigation-section";
export const MOBILE_NAVIGATION_ROOT_DATA_ATTRIBUTE =
  "data-mobile-navigation-root";
export const MOBILE_NAVIGATION_ACCORDION_DATA_ATTRIBUTE =
  "data-mobile-navigation-accordion";

export const MOBILE_NAVIGATION_ROOT_SELECTOR = `[${MOBILE_NAVIGATION_ROOT_DATA_ATTRIBUTE}]`;
export const MOBILE_NAVIGATION_SECTION_CONTROL_SELECTOR = `input[type="radio"][name="${MOBILE_NAVIGATION_SECTION_NAME}"]`;
export const MOBILE_NAVIGATION_ACCORDION_SELECTOR = `[${MOBILE_NAVIGATION_ACCORDION_DATA_ATTRIBUTE}]`;

export const MOBILE_NAVIGATION_ROOT_ATTRIBUTES = {
  [MOBILE_NAVIGATION_ROOT_DATA_ATTRIBUTE]: "",
} as const;

export const MOBILE_NAVIGATION_ACCORDION_ATTRIBUTES = {
  [MOBILE_NAVIGATION_ACCORDION_DATA_ATTRIBUTE]: "",
} as const;
