export const CATEGORY_TYPE_OPTIONS = [
  { id: "all", labelKey: "allProducts" },
  { id: "2", labelKey: "exclusive" },
  { id: "3", labelKey: "forHim" },
  { id: "4", labelKey: "forHer" },
  { id: "5", labelKey: "arabicScents" },
  { id: "6", labelKey: "niche" },
  { id: "7", labelKey: "homeFragrances" },
  { id: "8", labelKey: "oud" },
  { id: "9", labelKey: "body" },
  { id: "10", labelKey: "top12Brands" },
  { id: "20", labelKey: "exclusive" },
  { id: "30", labelKey: "forHim" },
  { id: "40", labelKey: "forHer" },
  { id: "50", labelKey: "arabicScents" },
  { id: "60", labelKey: "niche" },
  { id: "70", labelKey: "homeFragrances" },
  { id: "80", labelKey: "oud" },
  { id: "90", labelKey: "body" },
  { id: "100", labelKey: "top12Brands" },
] as const;
