// Client-safe environment variables
export const REST_BASE_URL = process.env.REST_BASE_URL!;
export const GRAPHQL_BASE_URL = process.env.GRAPHQL_BASE_URL!;
export const NEXT_PUBLIC_DOMAIN_AE = process.env.NEXT_PUBLIC_DOMAIN_AE!;
export const NEXT_PUBLIC_DOMAIN_GLOBAL = process.env.NEXT_PUBLIC_DOMAIN_GLOBAL!;
export const NEXT_PUBLIC_DOMAIN_KW = process.env.NEXT_PUBLIC_DOMAIN_KW!;
export const NEXT_PUBLIC_DOMAIN_OM = process.env.NEXT_PUBLIC_DOMAIN_OM!;
export const NEXT_PUBLIC_DOMAIN_SA = process.env.NEXT_PUBLIC_DOMAIN_SA!;
export const NEXT_PUBLIC_DOMAIN_IQ = process.env.NEXT_PUBLIC_DOMAIN_IQ!;
export const NEXT_PUBLIC_DOMAIN_BH = process.env.NEXT_PUBLIC_DOMAIN_BH!;
export const NEXT_PUBLIC_DOMAIN_BOULEVARD =
  process.env.NEXT_PUBLIC_DOMAIN_BOULEVARD!;
export const TAMARA_PUBLIC_KEY = process.env.NEXT_PUBLIC_TAMARA_PUBLIC_KEY!;
export const GOOGLE_MAPS_API_KEY = process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY!;
export const GOOGLE_MAPS_MAP_ID =
  process.env.NEXT_PUBLIC_GOOGLE_MAPS_MAP_ID || "DEMO_MAP_ID";
export const AMPLITUDE_API_KEY = process.env.NEXT_PUBLIC_AMPLITUDE_API_KEY;
export const CHECKOUT_PUBLIC_KEY = process.env.CHECKOUT_PUBLIC_API_KEY || "";
export const GOOGLE_ANALYTICS_ID = process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS_ID!;
export const GOOGLE_TAG_MANAGER_ID =
  process.env.NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID!;
export const GOOGLE_ANALYTICS_DEBUG_MODE =
  process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS_DEBUG_MODE === "true";
export const GOOGLE_ANALYTICS_WRAPPER_ENABLED =
  process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS_WRAPPER_ENABLED === "true";
export const NEW_RELIC_ENABLED =
  process.env.NEXT_PUBLIC_NEW_RELIC_ENABLED === "true";
export const APPLE_PAY_MERCHANT_IDENTIFIER_CHECKOUT =
  process.env.NEXT_PUBLIC_APPLE_PAY_MERCHANT_IDENTIFIER_CHECKOUT!;
export const APPLE_PAY_MERCHANT_IDENTIFIER_PAYFORT =
  process.env.NEXT_PUBLIC_APPLE_PAY_MERCHANT_IDENTIFIER_PAYFORT!;
export const INSIDER_PARTNER_NAME =
  process.env.NEXT_PUBLIC_INSIDER_PARTNER_NAME;
export const INSIDER_PARTNER_ID = process.env.NEXT_PUBLIC_INSIDER_PARTNER_ID;
